### ISSUE TITLE
Release artifacts to maven central

### ISSUE THREAD

**Issue by mtakaki** [dhatim/dropwizard-metrics-elasticsearch#3]
I tried using your library but it's  not available at maven central. Do you plan to have it released?
That would be nice so I don't need to clone and deploy the artifacts to my local repo.

**Comment by rgbj** [comment]
I just set up the publication to maven central; now waiting for central to sync, see https://oss.sonatype.org/content/repositories/releases/org/dhatim/io/dropwizard/dropwizard-metrics-elasticsearch/1.0.8/

**Comment by rgbj** [comment]
and here we go: http://search.maven.org/#search%7Cga%7C1%7Cg%3Aorg.dhatim.io.dropwizard%20a%3Adropwizard-metrics-elasticsearch

**Comment by mtakaki** [comment]
Thank you so much for releasing this!
